### ISSUE TITLE
Complete the OCU GUI and connection to the MongoDB database

### ISSUE THREAD

**Issue by mkmwila** [mmwila/ANS2017#1]
This task includes the creation of a missions ( Maps and destinations) , sending them to the world model ( MongoDB) and retrieving the unique id from MongoDB to be able to populate the drop down list on the OCU. The OCU should also implement the different modes of operation of the GBat ( Manual Mode, Joystick control and Autonomous) as well as the real time  feedback from the vehicle ( position on the map, speed etc..)

**Comment by PerseveranceMbewe** [comment]
connected the mongo database to the OCU
OCU can create a mission, start a mission and update the mission.

**Comment by PerseveranceMbewe** [comment]
working on the loading the map on the OCU
